version: 2
jobs:
    build:
        docker:
        -   image: circleci/openjdk:8-jdk

        working_directory: ~/rohitdm97/jbox
        environment:
            CIRCLE_ARTIFACTS: /tmp/rohitdm97/jbox/circleci-artifacts
            CIRCLE_TEST_REPORTS: /tmp/rohitdm97/jbox/circleci-test-results
            CIRCLE_ENV: test
        steps:
        -   checkout:
        -   run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        -   restore_cache:
                keys:
                - trx-audit-dependencies-{{ checksum "pom.xml" }}
                - trx-audit-dependencies-
                - trx-audit-
        -   run:
                name: run tests
                command: mvn clean test -Dspring.profiles.active=test
        -   save_cache:
                paths:
                - ~/.m2
                key: trx-audit-dependencies-{{ checksum "pom.xml" }}
        -   store_test_results:
            path: $CIRCLE_TEST_REPORTS
            # Save artifacts
        -   store_artifacts:
                path: $CIRCLE_ARTIFACTS
        -   store_artifacts:
                path: $CIRCLE_TEST_REPORTS

